name: Update Badge

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Esegue ogni notte a mezzanotte
  workflow_dispatch:     # Ti permette di avviarlo manualmente da GitHub

# Concede permessi di scrittura sul repository al bot di GitHub Actions
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Generate Badge
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: python generate_badge.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dynamic_card.svg projects_carousel.svg contribution_heatmap.svg walle_card.svg
          git status
          git diff-index --quiet HEAD || (git commit -m "Auto-update dynamic badges, projects carousel & heatmap [skip ci]" && git push)


